services:
  mongo:
    image: mongo:$MONGO_VERSION
    #container_name: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - mongo
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
  #---------------------------------------------------------------------------------------------------------------------
  mongo-express:
    image: mongo-express:$MONGO_EXPRESS_VERSION
    #container_name: mongo-express
    hostname: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    ports:
      - "8081:8081"
    networks:
      - mongo
    depends_on:
      - mongo
    links:
      - mongo
#---------------------------------------------------------------------------------------------------------------------
networks:
  mongo:
    driver: bridge
#---------------------------------------------------------------------------------------------------------------------
volumes:
  mongo-data:
  mongo-config:
