services:
  mongo:
    image: mongo:$MONGO_VERSION
    #container_name: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - databases
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
  #---------------------------------------------------------------------------------------------------------------------
  mongo-express:
    image: mongo-express:$MONGO_EXPRESS_VERSION
    #container_name: mongo-express
    hostname: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    ports:
      - "8081:8081"
    networks:
      - databases
    depends_on:
      - mongo
    links:
      - mongo
 #---------------------------------------------------------------------------------------------------------------------

  postgres:
    image: postgres
    hostname: postgreshost
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - databases
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
 #---------------------------------------------------------------------------------------------------------------------

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_HOST=postgreshost
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - databases
    depends_on:
      postgres:
        condition: service_healthy
    user: root
    volumes:
      - ./entrypoint.sh:/entrypoint_custom.sh
    entrypoint: /entrypoint_custom.sh


#---------------------------------------------------------------------------------------------------------------------
networks:
  databases:
    driver: bridge
#---------------------------------------------------------------------------------------------------------------------
volumes:
  mongo-data:
  mongo-config:
  postgres_data:
